### ISSUE TITLE
buchheim layout overlaping 

### ISSUE THREAD

**Issue by zvnkk** [JuliaGraphs/NetworkLayout.jl#60]
I m using GraphRecipies for plotting given Buchheim layout the output as method parameter is the  following
![image](https://github.com/JuliaGraphs/NetworkLayout.jl/assets/143273920/ff1c1e56-3d5c-4249-9750-fe229564a1b7)
how to make graph non-overlaping, i could not find any parameter for this ? (there is :nodesize parameter for layout_kw but this does nothing ) 

please help
the thing is that for node weight parameters i have 0 and that is causing the conflict

**Comment by hexaeder** [comment]
`GraphRecipes` uses the `nodeweight` to forward it to node size:

https://github.com/JuliaPlots/GraphRecipes.jl/blob/f2d932900febcf0d89851567fba52927164d1591/src/graph_layouts.jl#L284-L286

so don't set it to 0 then? Because 0 nodesize will lead to those results:

```julia
using Graphs, GraphMakie, GLMakie, NetworkLayout
g = SimpleDiGraph(16)
add_edge!(g, 1, 2)
add_edge!(g, 1, 3)
add_edge!(g, 2, 4)
add_edge!(g, 2, 5)
add_edge!(g, 2, 6)
add_edge!(g, 3, 7)
add_edge!(g, 3, 8)
add_edge!(g, 4, 9)
add_edge!(g, 5, 10)
add_edge!(g, 6, 11)
add_edge!(g, 7, 12)
add_edge!(g, 7, 13)
add_edge!(g, 8, 14)
add_edge!(g, 12, 15)
add_edge!(g, 13, 16)

graphplot(g, layout=Buchheim())
```
![grafik](https://github.com/JuliaGraphs/NetworkLayout.jl/assets/35867212/b49e9de4-78c7-49d8-b0b1-2deb8f48cf92)

```
graphplot(g, layout=Buchheim(;nodesize=Float64[0 for i in 1:16]))
```
![grafik](https://github.com/JuliaGraphs/NetworkLayout.jl/assets/35867212/c0bea3f1-9a2d-42e3-84e4-b49d953077c3)

**Comment by zvnkk** [comment]
Thanks for the feedback, figured everything out.
